base_path: &base_path runs/cifar10_mergenas_bs64/
root_path: &root_path !join [*base_path, retrain/]
epoch: &epoch 600
accumulate_gradient: &acc_grad 1

auxiliary_model: &aux
  submodule_name: src.models.BaseModel
  args:
    output_ch: &output_ch 10
    architecture:
      - input_idx: -1 # 0
        submodule_name: PoolBNAct
        args: 
          pool: avg
          kernel: 5
          stride: 3
          pad: 0
          act: False
          bn: False
          count_include_pad: False
      - input_idx: -1 # 1
        submodule_name: ConvBNAct
        args: 
          out_channel: 128
          kernel: 1
          act: torch.nn.ReLU
          bn: torch.nn.BatchNorm2d
      - input_idx: -1 # 2
        submodule_name: ConvBNAct
        args: 
          out_channel: 768
          kernel: 2
          act: torch.nn.ReLU
          bn: torch.nn.BatchNorm2d
      - input_idx: -1 # 3
        submodule_name: LinearBNAct
        is_outlayer: True
        args: 
          out_channel: *output_ch
          act: False
          bn: False

criterion: &criterion
  submodule_name: src.criterions.CriterionWithAux
  args:
    criterion_or_cfg:
      submodule_name: torch.nn.CrossEntropyLoss
    in_channel: 576
    out_channel: *output_ch
    auxiliary_or_cfg: *aux
    auxiliary_weight: 0.4

optimizer: &optimizer
  submodule_name: torch.optim.SGD
  args:
    params:
    lr: 0.025
    momentum: 0.9
    weight_decay: 3.e-4

lr_scheduler: &scheduler
  submodule_name: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    optimizer: 
    T_max: *epoch

hooks: &hooks
  opt_hook:
    submodule_name: OptHOOK
    args:
      grad_clip: 5
      priority: 0
      accumulate_gradient: *acc_grad
  
  lr_scheduler_hook:
    submodule_name: LrScheduleHOOK
    args: 
      priority: 5
      mode: epoch

  drop_path_hook:
    submodule_name: DropPathProbHOOK
    args:
      mode: epoch
      apply_period: 1
      priority: 5

  eval_hook:
    submodule_name: EvalAccHOOK
    args: 
      priority: 5
  
  ddp_hook:
    submodule_name: DDPHOOK
    args:
      priority: 10
  
  
  log_hook:
    submodule_name: LogHOOK
    args:
      logger_name: TrainPip
      log_path: !join [*root_path, test.log]
      print_freq: 100
      only_master: True
      priority: 20
  
  ckpt_hook:
    submodule_name: CkptHOOK
    args:
      save_root: !join [*root_path, ckpt/]
      pretrain: 
      only_master: True
      priority: 20
  

engine:
  submodule_name: NNEngine
  args:
    data: !cross_ref [cfg/dataset/cifar10.yaml]
    model: !cross_ref [!join [*base_path, arch/architecture_49.yaml]]
    criterion: *criterion
    optimizer: *optimizer
    lr_scheduler: *scheduler
    hooks: *hooks
    amp: false

