root_path: &root_path runs/cifar10_darts/
epoch: &epoch 50
accumulate_gradient: &acc_grad 1
amp: False

data: cfg/dataset/cifar10_search.yaml

model: cfg/model/darts.yaml

criterion: 
  submodule_name: torch.nn.CrossEntropyLoss

optimizer: &optimizer
  submodule_name: torch.optim.SGD
  args:
    params:
    lr: 0.025
    momentum: 0.9
    weight_decay: 3.e-4

lr_scheduler: &scheduler
  submodule_name: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    optimizer: 
    T_max: *epoch
    eta_min: 0.001

hooks:
  opt_hook:
    submodule_name: OptHOOK
    args:
      priority: 0
      accumulate_gradient: *acc_grad
  
  lr_scheduler_hook:
    submodule_name: LrScheduleHOOK
    args: 
      priority: 5
      mode: epoch

  darts_hook:
    submodule_name: DARTSHOOK
    args:
      optimizer_cfg:
        submodule_name: torch.optim.Adam
        args:
          lr: 3.e-4
          betas: (0.5, 0.999)
          weight_decay: 1.e-3
      dataloader_name: search_val
      criterion_cfg:
        submodule_name: torch.nn.CrossEntropyLoss
      update_freq: 5
      accumulate_gradient: *acc_grad
      priority:
      save_root: !join [*root_path, arch/]
  
  eval_hook:
    submodule_name: EvalAccHOOK
    args: 
      priority: 5
  
  ddp_hook:
    submodule_name: DDPHOOK
    args:
      priority: 10
  
  
  log_hook:
    submodule_name: LogHOOK
    args:
      logger_name: TrainPip
      log_path: !join [*root_path, test.log]
      print_freq: 100
      only_master: True
      priority: 20
  
  ckpt_hook:
    submodule_name: CkptHOOK
    args:
      save_root: !join [*root_path, ckpt/]
      pretrain: 
      only_master: True
      priority: 20
  
