root_path: &root_path runs/cifar10_res18/
epoch: &epoch 300
accumulate_gradient: &acc_grad 1
amp: False # True

data: cfg/dataset/imagenet.yaml

criterion: cfg/criterion/cross_entropy.yaml

model: cfg/model/mobilenetv2.yaml

optimizer: &optimizer
  submodule_name: SGD
  module_name: .optim
  package_path: torch
  args:
    params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 3.0e-5

# optimizer: &optimizer
#   submodule_name: AdamW
#   module_name: .optim
#   package_path: torch
#   args:
#     params:
#     lr: 4.e-3
#     weight_decay: 0.05

lr_scheduler: &scheduler
  submodule_name: CosineAnnealingLR
  module_name: .optim.lr_scheduler
  package_path: torch
  args:
    optimizer: 
    T_max: *epoch 
    eta_min: 1.e-6

opt_hook:
  hook_name: OptHOOK
  hook_args:
    optimizer: 
    priority: 1
    accumulate_gradient: *acc_grad

lr_scheduler_hook:
  hook_name: LrScheduleHOOK
  hook_args: 
    lr_scheduler:
    priority: 2
    mode: epoch

eval_hook:
  hook_name: EvalAccHOOK
  hook_args: 
    priority: 0

ddp_hook:
  hook_name: DDPHOOK
  hook_args:
    priority: 5


log_hook:
  hook_name: LogHOOK
  hook_args:
    logger_name: TrainPip
    log_path: !join [*root_path, test.log]
    print_freq: 50
    only_master: True
    priority: 10

ckpt_hook:
  hook_name: CkptHOOK
  hook_args:
    save_root: !join [*root_path, ckpt/]
    pretrain: 
    only_master: True
    priority: 20

# warmup_hook:
#   hook_name: WarmupHOOK
#   hook_args:
#     max_iter: 1000
#     warmup_init_lr_rate: 1.e-3
#     priority: 0
#     accumulate_gradient: *acc_grad
