num_classes: 10
input_size: 32

dataset:
  train:
    submodule_name: src.datasets.CIFAR10
    dataset_args:
      root: ./data/
      train: True
      download: True
      transform: !get_module [src.datasets.cifar.get_transforms, {cutout: True, cutout_length: 16, cutout_prob: 1.0}]
  val:
    submodule_name: src.datasets.CIFAR10
    dataset_args:
      root: ./data/
      train: False
      download: True
      transform: !get_module [src.datasets.cifar.get_transforms, {cutout: True, cutout_length: 16, cutout_prob: 1.0}]

dataloader:
  train:
    dataset_name: train
    dataloader_args:
      batch_size: 96
      pin_memory: True
      num_workers: 4
  val:
    dataset_name: val
    use_dist: False
    dataloader_args:
      batch_size: 96
      pin_memory: True
      num_workers: 4
      shuffle: False
