num_classes: 1000
input_size: 224

dataset:
  train:
    submodule_name: src.datasets.IMAGENET
    dataset_args:
      root: ./data/imagenet/train
      train: True
      transform: default
  val:
    submodule_name: src.datasets.IMAGENET
    dataset_args:
      root: ./data/imagenet/val
      train: False
      transform: default

dataloader:
  train:
    dataset_name: train
    dataloader_args:
      batch_size: 64
      pin_memory: True
      num_workers: 8
  val:
    dataset_name: val
    use_dist: False
    dataloader_args:
      batch_size: 64
      pin_memory: True
      num_workers: 4

